### ISSUE TITLE
getting RuntimeError - python setup.py import_cldr, but no setup.py to be run

### ISSUE THREAD

**Issue by peter-kolenic** [gae-init/gae-init-babel#53]
Hi,

whatever i do, i'm unable to make gae-init-babel returning anything besides error page - i always get response with:
> RuntimeError: The babel data files are not available. This usually happens because you are using a source checkout from Babel and you did not build the data files.  Just make sure to run "python setup.py import_cldr" before installing the library.

I must be starting in some wrong way or whatever. 
./run.py -i
gives as the first error: 
> pkg_resources.VersionConflict: (Babel 2.0.dev0-20150518 (/opt/src/gae-init-babel/temp/venv/lib/python2.7/site-packages), Requirement.parse('Babel>=0.8'))

end then few:
> RuntimeError: The babel data files are not available. This usually happens because you are using a source checkout from Babel and you did not build the data files.  Just make sure to run "python setup.py import_cldr" before installing the library.

The same goes with ./run.py -u, plus
> IOError: [Errno 2] No such file or directory: 'main/translations/messages.pot'
> pybabel compile -f -d main/translations
> Usage: pybabel compile [options] 
> pybabel: error: no message catalogs found 

What is the correct way of initialising the project ? 

(if for it was for any use, whole transcript is here:
https://gist.github.com/peter-kolenic/055d663ffe08f7c5d565 )

**Comment by lipis** [comment]
I believe I totally missed that one :( Many things have changed since and you should not have any issues now.. (if still care)
