### ISSUE TITLE
CSS error of caret in dropdown.less

### ISSUE THREAD

**Issue by bangive** [gae-init/gae-init-babel#54]
This happend in Firefox
The value of border-top is "dashed" so the caret is displayed wrong. If i change to "solid" the caret is displayed right.

**Comment by lipis** [comment]
are you sure this is not a [Bootstrap](https://github.com/twbs/bootstrap)'s issue?

**Comment by bangive** [comment]
i think this is bootstrap's issiue. But why on the site http://babel.gae-init.appspot.com/ the css value of caret is "solid".

**Comment by lipis** [comment]
so it's correct?

**Comment by bangive** [comment]
yes, it's boostrap's issue. The issue is here: [.caret rendering problem in firefox](https://github.com/twbs/bootstrap/issues/16657)
