### ISSUE TITLE
I can't able to run gae-init-babel

### ISSUE THREAD

**Issue by sparkline-annalyn** [gae-init/gae-init-babel#57]
Hi,

I am very new in gae-init but I need to work with the translation of text content, I already install the gae-init-babel in my local this is how it looks:

![image](https://cloud.githubusercontent.com/assets/15081968/11088340/79476082-889c-11e5-81ce-a1bb3733e8c3.png)

but once I change the flag in other flag or language, for example the Polski changing in the content doesn't effect on my local.

![image](https://cloud.githubusercontent.com/assets/15081968/11088474/7a256930-889d-11e5-9946-b654f76267bc.png)

Please inform me if I need to do some procedure for I can able to run the gae-init-label the way it should be. Hoping for your immediate response, any help will be much appreciated.

**Comment by lipis** [comment]
You have to do a few things before seeing things:

```
./run.py -u
```

Will scan the whole project to see what is needed to be translated, generate the files and compile them for use. So run this the first time.. then check the folder `main/translations/` and edit them accordignly. After you added some translations.. run the above command again and you should see the translated text. You can download some translations from here: https://crowdin.com/project/gae-init to begin with if you like.

**Comment by sparkline-annalyn** [comment]
Hi Lipis,

Thanks I can able to run gae-init-label in my local, I already downloaded some translation from https://crowdin.com/project/gae-init and save it from translation folder.

Cheers, you have a great app!

**Comment by sparkline-annalyn** [comment]
Hi Lipis,

But I can't able to add new language like for example Philippines(tagalog),

![image](https://cloud.githubusercontent.com/assets/15081968/11110137/74ef5980-8933-11e5-85c8-528cc43b2b23.png)


What is the possible problem with this?
Any help will be much appreciated. Thanks!

**Comment by sparkline-annalyn** [comment]
Hi Lipis,

I just want to ask I have an existing project where I would like to add the gae-init-label, could you please help me on how to that?

Thanks!
