### ISSUE TITLE
Existing Project

### ISSUE THREAD

**Issue by sparkline-annalyn** [gae-init/gae-init-babel#58]
Hi Lipis,

I just want to ask I have an existing project where I would like to add the gae-init-label, could you please help me on how to that?

Thanks!

**Comment by lipis** [comment]
If you have an existing project that you started with `gae-init` then you could do the following:

Create a new branch just in case something will go wrong:

```
git checkout -b babel-integration
```

and then add the new remote and pull from there

```
git remote add babel https://github.com/gae-init/gae-init-babel.git
git pull babel master
```

Most likely you'll have bunch of conflicts (depends on how changes you had) but if you'll manage to resolve them, you should be good to go.

**Comment by sparkline-annalyn** [comment]
I always got this error:

![image](https://cloud.githubusercontent.com/assets/15081968/11115622/c5710d98-8967-11e5-9b09-085ce43a6b39.png)

Do you have any idea on how to fix this?

**Comment by lipis** [comment]
Do you have that in your model?

https://github.com/gae-init/gae-init-babel/blob/master/main/model/config.py#L23

**Comment by sparkline-annalyn** [comment]
Yes I have

**Comment by sparkline-annalyn** [comment]
How about this error?

![image](https://cloud.githubusercontent.com/assets/15081968/11116341/121f0848-896d-11e5-9a3a-b1e54b44f839.png)

Do you have any idea how to fix this?

**Comment by lipis** [comment]
Not really.. except the obvious.. that the `pwd` is not found..

**Comment by sparkline-annalyn** [comment]
Okay, I just want also to know where will you put your initialization for {{request.locale}}?

**Comment by sparkline-annalyn** [comment]
Hi,

I just want to know how will I add new text to be translated on my project? I tried to add it in message. po and type run.py -u it's not working. I also got this error:

![image](https://cloud.githubusercontent.com/assets/15081968/11139935/17847414-8a10-11e5-851a-7f301cc8527e.png)

Thanks, I hope I make sense with you

**Comment by sparkline-annalyn** [comment]
Hi Lipis, 

I fixed the issues I encountered on installing the babel on my local but I want to ask if is it possible if could put my text in a variable and then instead of text I will used the variable in page?

Thanks, hoping for immediate response.

**Comment by lipis** [comment]
Is that still an issue? Bunch of things updated since then.. if you still have issues we'll reopen it..
